# Generated by Django 6.0.4 on 2026-09-03 17:57

import django.core.validators
import django.db.models.deletion
import shifts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_add_timestamps_and_rule_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='schedule',
            new_name='shifts_sche_date_a9c6e7_idx',
            old_name='shifts_sche_date_idx',
        ),
        migrations.RenameIndex(
            model_name='schedule',
            new_name='shifts_sche_employe_218e22_idx',
            old_name='shifts_sche_emp_date_idx',
        ),
        migrations.AddField(
            model_name='employee',
            name='organization_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='organization_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulingrule',
            name='organization_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='organization_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='shifts.employee'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='shift_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='shifts.shifttype'),
        ),
        migrations.AlterField(
            model_name='schedulingrule',
            name='avoid_consecutive_nights',
            field=models.BooleanField(default=True, help_text='Evitar dois turnos noturnos seguidos para o mesmo funcionário.'),
        ),
        migrations.AlterField(
            model_name='schedulingrule',
            name='mandatory_rest_days',
            field=models.PositiveIntegerField(default=1, help_text='Dias obrigatórios de descanso após atingir o máximo consecutivo.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='schedulingrule',
            name='max_consecutive_days',
            field=models.PositiveIntegerField(default=5, help_text='Máximo de dias consecutivos de trabalho permitidos.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, validators=[shifts.models.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('organization_id', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='shifttype',
            unique_together={('organization_id', 'name')},
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['organization_id'], name='shifts_sche_organiz_aa3f16_idx'),
        ),
    ]
